## NumPy的基本使用--改变形状、转置和换轴

In [1]:
import numpy as np

### 1. 改变数组形状：reshape

`numpy.reshape()`用于改变数组的形状，而不改变其数据内容。

In [2]:
arr = np.arange(16)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [4]:
arr.reshape(4, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [5]:
arr.reshape(2, 2, 4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

### 2. 转置：transpose

转置是一种特殊的数组重组形式，调用转置后返回底层数据的视图而不需要复制任何内容。

In [6]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

In [7]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
# 行变成了列，列变成了行
arr.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [9]:
# T也是transpose的简写
arr.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

### 3. 换轴: swapaxes

`swapaxes()`方法是交换数组中的2个轴，接受2个参数，分别是要交换的轴的编号。

In [10]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
arr.swapaxes(0, 1)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [12]:
# 来个三维数组试一下
arr3 = np.arange(45).reshape(3, 3, 5)
arr3

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]],

       [[30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44]]])

In [13]:
arr3.shape, arr3.ndim

((3, 3, 5), 3)

In [14]:
# 第1个和第2个轴互换一下
arr3.swapaxes(0, 1)

array([[[ 0,  1,  2,  3,  4],
        [15, 16, 17, 18, 19],
        [30, 31, 32, 33, 34]],

       [[ 5,  6,  7,  8,  9],
        [20, 21, 22, 23, 24],
        [35, 36, 37, 38, 39]],

       [[10, 11, 12, 13, 14],
        [25, 26, 27, 28, 29],
        [40, 41, 42, 43, 44]]])

In [15]:
# 看下arr3的T
arr3.T

array([[[ 0, 15, 30],
        [ 5, 20, 35],
        [10, 25, 40]],

       [[ 1, 16, 31],
        [ 6, 21, 36],
        [11, 26, 41]],

       [[ 2, 17, 32],
        [ 7, 22, 37],
        [12, 27, 42]],

       [[ 3, 18, 33],
        [ 8, 23, 38],
        [13, 28, 43]],

       [[ 4, 19, 34],
        [ 9, 24, 39],
        [14, 29, 44]]])