## NumPy的基本使用--通用函数

In [1]:
import numpy as np

In [2]:
# 禁止科学计算法
np.set_printoptions(suppress=True)

### 1. 一元通用函数

 函数名 | 描述 
 :--- | ---
 abs、fabs | 逐元素地计算整数、浮点数或复数的绝对值 
 sqrt | 计算每个元素的平方根 ${arr}^{0.5}$ 或   $\sqrt[2]{arr}$
 square | 计算每个元素的平方 ${arr}^2$

### 1.1 绝对值：abs

In [3]:
arr = np.arange(4)
arr

array([0, 1, 2, 3])

In [4]:
# 计算绝对值
np.abs(arr)

array([0, 1, 2, 3])

In [5]:
np.abs(arr * -2)

array([0, 2, 4, 6])

### 1.2 平方根：sqrt

In [6]:
arr = np.array([0, 1, 4, 9, 25])
arr

array([ 0,  1,  4,  9, 25])

In [7]:
np.sqrt(arr)

array([0., 1., 2., 3., 5.])

### 1.3 平方：square

In [8]:
arr = np.arange(1, 6)
arr

array([1, 2, 3, 4, 5])

In [9]:
np.square(arr)

array([ 1,  4,  9, 16, 25])

### 2.二元通用函数

二元函数，接收两个数组并返回一个数组作为结果，因此称其为二元通用函数。

函数名 | 描述
--- | ---
add | 将2个数组的对应元素相加
subtract | 减
multiply | 将数组的对应元素相乘
divide, floor_divide | 除或整除（地板除，余数不要）
power | 将第2个数组的元素作为第一个元素的幂次方
mod | 按元素的求模计算（即得到除法的余数）

#### 2.1 相加：add

In [10]:
arr1 = np.array([1.0, 2.0, 3.0, 4.0])
arr2 = np.array([4.0, 5.0, 6.0, 7.0])

In [11]:
arr1, arr2

(array([1., 2., 3., 4.]), array([4., 5., 6., 7.]))

In [12]:
# 逐元素相加
np.add(arr1, arr2)

array([ 5.,  7.,  9., 11.])

#### 2.2 减：subtract

In [13]:
np.subtract(arr1, arr2)

array([-3., -3., -3., -3.])

#### 2.3 乘：multiply

In [14]:
np.multiply(arr1, arr2)

array([ 4., 10., 18., 28.])

#### 2.4 除：divide和floor_divide

In [15]:
arr1

array([1., 2., 3., 4.])

In [16]:
arr2

array([4., 5., 6., 7.])

In [17]:
# 除
np.divide(arr2, arr1)

array([4.  , 2.5 , 2.  , 1.75])

In [18]:
# 地板除
np.floor_divide(arr2, arr1)

array([4., 2., 2., 1.])

#### 2.5 幂次方：power

In [19]:
np.power(arr2, arr1)

array([   4.,   25.,  216., 2401.])

In [20]:
# 计算一下7的4次方
7 ** 4

2401

#### 2.6 除法的余数

In [21]:
np.mod(arr2, arr1)

array([0., 1., 0., 3.])