## NumPy基本使用--切片和索引

In [1]:
import numpy as np

# 禁止科学技术方式输出
np.set_printoptions(suppress=True)

### 1. 切片

In [2]:
arr = np.arange(1, 20, 2)
arr

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [3]:
# 获取第3个元素
arr[2]

5

In [4]:
# 获取前面5个元素
arr[:5]

array([1, 3, 5, 7, 9])

In [5]:
# 获取后面3个元素
arr[-3:]

array([15, 17, 19])

In [6]:
# 获取全部元素
arr[:]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [7]:
# 获取元素，格2个取一个
arr[::2]

array([ 1,  5,  9, 13, 17])

### 2. 索引元素

为了让0.1,0.11， 1000一起答应输出的时候，不要以科学计数法展示，可以设置`NumPy`的打印选项。

```python
np.set_printoptions(suppress=True)
```

In [8]:
arr = np.array([
    [
        [0.1, 0.2, 0.3],
        [0.11, 0.22, 0.33],
        [0.111, 0.222, 0.333]
    ],
    [
        [1.0, 2.0, 3.0],
        [1.2, 2.1, 3.1],
        [1.3, 2.3, 3.3],
    ],
    [
        [100.0, 200.0, 300.0],
        [1000, 2000, 3000],
        [10000, 20000, 30000],
    ]
]) 

In [9]:
arr

array([[[    0.1  ,     0.2  ,     0.3  ],
        [    0.11 ,     0.22 ,     0.33 ],
        [    0.111,     0.222,     0.333]],

       [[    1.   ,     2.   ,     3.   ],
        [    1.2  ,     2.1  ,     3.1  ],
        [    1.3  ,     2.3  ,     3.3  ]],

       [[  100.   ,   200.   ,   300.   ],
        [ 1000.   ,  2000.   ,  3000.   ],
        [10000.   , 20000.   , 30000.   ]]])

In [10]:
arr.shape, arr.ndim

((3, 3, 3), 3)

**三维那么索引的时候可以设置三个值**

In [11]:
arr[0]

array([[0.1  , 0.2  , 0.3  ],
       [0.11 , 0.22 , 0.33 ],
       [0.111, 0.222, 0.333]])

In [12]:
arr[0,0]

array([0.1, 0.2, 0.3])

In [13]:
arr[0, 0, 1]

0.2

**取出第1维中的所有行，第2维只取第2个数，第三维选全部**

In [14]:
arr[:,1,:]

array([[   0.11,    0.22,    0.33],
       [   1.2 ,    2.1 ,    3.1 ],
       [1000.  , 2000.  , 3000.  ]])

**取出第1维中的所有行，第2维的支取第1个数，第三位只取第3个数**

In [15]:
arr[:,0,2]

array([  0.3,   3. , 300. ])

**取出3维中的某个元素**

In [16]:
# 方式一：
arr[1,1,1]

2.1

In [17]:
# 方式二：
arr[1][1][1]

2.1