## NumPy数组算术

In [1]:
import numpy as np

### 1. 准备2个数组

In [2]:
arr1 = np.array([
    [1.0, 2.0],
    [3.0, 4.0],
])

arr2 = np.array([
    [1.5, 2.0],
    [2.0, 4.0],
])

In [3]:
arr1

array([[1., 2.],
       [3., 4.]])

In [4]:
arr2

array([[1.5, 2. ],
       [2. , 4. ]])

### 2. 加减乘除

#### 2.1 加

In [5]:
# 加法
arr1 + 1

array([[2., 3.],
       [4., 5.]])

In [6]:
arr1 + arr2

array([[2.5, 4. ],
       [5. , 8. ]])

#### 2.2 减

In [7]:
arr1 - arr2

array([[-0.5,  0. ],
       [ 1. ,  0. ]])

#### 2.3 乘

相乘有`*`操作符是元素级操作，`.dot`方法执行的是矩阵乘法，这2个概念是完全不同的运算。

In [8]:
arr1, arr2

(array([[1., 2.],
        [3., 4.]]),
 array([[1.5, 2. ],
        [2. , 4. ]]))

##### 元素-wise乘法

In [9]:
arr1 * arr2

array([[ 1.5,  4. ],
       [ 6. , 16. ]])

##### 矩阵乘法
arr1的第`i`行拿出来与`arr2`的第`j`列各元素相乘，然后相加后的和为新的数组`ij`位的元素。

比如`01`元素是：`[1.0, 2.0]`与`[2.0, 4.0]`元素相乘后的和`10.0`。

In [10]:
arr1.dot(arr2)

array([[ 5.5, 10. ],
       [12.5, 22. ]])

#### 2.4 除

In [11]:
arr1

array([[1., 2.],
       [3., 4.]])

In [12]:
1.0 / arr1

array([[1.        , 0.5       ],
       [0.33333333, 0.25      ]])