## NumPy数学计算--基础统计方法

In [1]:
import numpy as np
# 调整打印输出选项
np.set_printoptions(suppress=True)

方法 | 描述
--- | --- 
sum | 沿着轴向计算所有元素的累计和
mean | 计算平均值
std, var | 标准差和方差
min, max | 计算最小、最大值
argmin, argmax | 最小值和最大值的位置
cumsum | 从0开始元素累积**和**
cumprod | 从1开始元素累积**积**

### 1. 累计和：sum

In [2]:
arr = np.array([1.0, 2.0, 3.0])
arr

array([1., 2., 3.])

In [3]:
arr.sum()

6.0

### 2. 平均值：mean

In [4]:
arr

array([1., 2., 3.])

In [5]:
arr.mean()

2.0

### 3. 标准差和方差

In [6]:
arr

array([1., 2., 3.])

#### 方差

> 方差是各个数据与其平均值之差的平方的平均数。

In [7]:
# 手动计算方差
((1.0 - 2.0) ** 2 + (2.0 - 2.0) ** 2 + (3.0 - 2.0) ** 2) / 3

0.6666666666666666

In [8]:
# 直接用var()方法计算方差
arr.var()

0.6666666666666666

#### 标准差

> 标准差是方差的平方根。$\sqrt[2]{arr.var()}$

In [9]:
arr.var()**0.5

0.816496580927726

In [10]:
arr.std()

0.816496580927726

### 4. 最小值和最大值：min、max

In [11]:
arr

array([1., 2., 3.])

In [12]:
arr.min()

1.0

In [13]:
arr.max()

3.0

### 5. 最小值和最大值的位置：argmin, argmax

In [14]:
arr.argmin(), arr.argmax()

(0, 2)

### 6. cumsum

从第0个元素开始累计的和。

In [15]:
arr

array([1., 2., 3.])

In [16]:
# 手动计算
0+1.0, 0 + 1.0 + 2.0, 0 + 1.0 + 2.0 + 3.0

(1.0, 3.0, 6.0)

In [17]:
arr.cumsum()

array([1., 3., 6.])

### 7. cumprod

从1开始元素累积的积

In [18]:
arr = np.arange(2, 8, 2)
arr

array([2, 4, 6])

In [19]:
# 手动计算
1*2, 1*2*4, 1*2*4*6

(2, 8, 48)

In [20]:
arr.cumprod()

array([ 2,  8, 48])

In [22]:
arr

array([2, 4, 6])