## np.lib.stride_tricks.as_strided

In [1]:
import numpy as np

In [2]:
arr = np.array(range(1, 17), dtype=np.int32)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16],
      dtype=int32)

In [3]:
arr.strides

(4,)

In [4]:
arr1 = np.lib.stride_tricks.as_strided(arr, shape=(2, 8))
arr1

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16]], dtype=int32)

In [5]:
arr1.strides

(32, 4)

In [6]:
arr2 = np.lib.stride_tricks.as_strided(arr, shape=(3, 8), strides=(4, 4))
arr2

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 2,  3,  4,  5,  6,  7,  8,  9],
       [ 3,  4,  5,  6,  7,  8,  9, 10]], dtype=int32)

In [7]:
arr2.strides

(4, 4)

In [8]:
np.moveaxis(arr2, -1, -2)

array([[ 1,  2,  3],
       [ 2,  3,  4],
       [ 3,  4,  5],
       [ 4,  5,  6],
       [ 5,  6,  7],
       [ 6,  7,  8],
       [ 7,  8,  9],
       [ 8,  9, 10]], dtype=int32)

In [9]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16],
      dtype=int32)

In [10]:
s = slice(0, None, 2)

In [11]:
arr[s]

array([ 1,  3,  5,  7,  9, 11, 13, 15], dtype=int32)

In [12]:
xw = np.array(range(1127531))
xw.shape

(1127531,)

In [13]:
x = xw[slice(0,None, 320)]
x.shape

(3524,)

In [14]:
x[0:10]

array([   0,  320,  640,  960, 1280, 1600, 1920, 2240, 2560, 2880])

In [15]:
x[-10:]

array([1124480, 1124800, 1125120, 1125440, 1125760, 1126080, 1126400,
       1126720, 1127040, 1127360])