## NumPy函数之---pad

> `NumPy.pad()`函数是`NumPy`库中的一个功能，用于在数组的边缘填充(添加)值。
> 在图像处理、信号处理或者数据分析时，需要保持数据的尺寸一致性、添加边界条件等的时候非常有用。
> 该函数提供了灵活的方式来控制如何以及在哪里添加这些填充值。

函数：
```python
numpy.pad(array, pad_width, model='constant', **kwargs)
```
- `array`: 输入的数组，可以是一维、多维数组。
- `pad_width`: 指定在数组每一边缘添加填充的宽度。
  > 它可以是一个数字、元组或者列表。对于多维数组，它应是一个列表，其中每个元素对应数组对应维度的填充宽度。
  > 例如：`((before_1, after_1), ...... ,(before_N, after_N))`指定了每一维的前填充和后填充的宽度。

- `mode`: 指定填充的类型：默认是`constant`
  > 另外有：'edge','linear_ramp'、'maximum'、'mean'、'median'、'minimum'、'reflect'、'symmetric'、'wrap'等
  > 不同的模式决定了如何计算填充的值。

- `**kwargs`: 额外的关键字参数，具体取决于所选的填充模式。
  > 例如：`mode='constant'`时，通常会提供`constant_values`参数来指定填充的具体值。

In [1]:
import numpy as np

### 示例1

#### 一维数组填充

In [2]:
# 先创建一个数组
arr = np.array(range(1, 10))
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
# 使用常量填充，宽度为(2, 2),既前后各加2个值，constant_values默认值是0
padded_arr1 = np.pad(arr, pad_width=(2,2), mode='constant')
padded_arr1

array([0, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 0])

In [4]:
# arr是不会变化的
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
# 使用常量填充，宽度为(2, 2),既前后各加2个值，constant_values设置为11
padded_arr2 = np.pad(arr, pad_width=(2,2), mode='constant', constant_values=11)
padded_arr2

array([11, 11,  1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 11])

In [6]:
# 使用常量填充，宽度为(2, 2),既前后各加2个值，constant_values设置为(11, 22)
padded_arr3 = np.pad(arr, pad_width=(2,2), mode='constant', constant_values=(11,22))
padded_arr3

array([11, 11,  1,  2,  3,  4,  5,  6,  7,  8,  9, 22, 22])

#### 二维数组填充

In [7]:
arr2 = np.array(range(1, 16)).reshape((3, 5))
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [8]:
# 第一维度：(2,1): 那么就是行，前面添加2行，后面添加1行
# 第二维度：(1,2): 就是前面添加1列，后面添加2行
padded_2d_01 = np.pad(arr2, pad_width=((2, 1), (1, 2)), mode='constant')
padded_2d_01

array([[ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  1,  2,  3,  4,  5,  0,  0],
       [ 0,  6,  7,  8,  9, 10,  0,  0],
       [ 0, 11, 12, 13, 14, 15,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0]])

In [9]:
# 我们来把模式设置为edge看下
padded_2d_02 = np.pad(arr2, pad_width=((2, 1), (1, 2)), mode='edge')
padded_2d_02

array([[ 1,  1,  2,  3,  4,  5,  5,  5],
       [ 1,  1,  2,  3,  4,  5,  5,  5],
       [ 1,  1,  2,  3,  4,  5,  5,  5],
       [ 6,  6,  7,  8,  9, 10, 10, 10],
       [11, 11, 12, 13, 14, 15, 15, 15],
       [11, 11, 12, 13, 14, 15, 15, 15]])

In [10]:
arr2.strides

(40, 8)

In [11]:
padded_2d_02.strides

(64, 8)

In [12]:
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [13]:
padded_2d_02.strides[-1]

8

In [14]:
padded_2d_02.strides + tuple([padded_2d_02.strides[-1]])

(64, 8, 8)