## 01-张量的基本使用

In [1]:
import torch

### 1.1 从Python列表到PyTorch张量

In [2]:
a = [1.1, 2.2, 3.3, 4.4,  5.5]

In [3]:
a[0], a[2], a[3]

(1.1, 3.3, 4.4)

In [4]:
t1 = torch.tensor([1.1, 2.2, 3.3, 4.4,  5.5])

In [5]:
type(t1)

torch.Tensor

In [6]:
t1

tensor([1.1000, 2.2000, 3.3000, 4.4000, 5.5000])

In [7]:
t1[0] = 1.6
t1[1] = 2.6
t1[2] = 3.6
t1[3] = 4.6
t1

tensor([1.6000, 2.6000, 3.6000, 4.6000, 5.5000])

In [8]:
print(t1[0], t1[3])
print(t1[:2])
print(t1[-2:])
print(t1[::2])
print(t1[3:])

tensor(1.6000) tensor(4.6000)
tensor([1.6000, 2.6000])
tensor([4.6000, 5.5000])
tensor([1.6000, 3.6000, 5.5000])
tensor([4.6000, 5.5000])


In [9]:
# 查看t1的形状和类型
t1.shape, t1.dtype

(torch.Size([5]), torch.float32)

虽然表面上上面的`a`和`t1`，张量和number类型的list没有太大区别，但是它们实际上是完全不同的东西。

> Python列表或者数字元组是在内存中单独分配的Python对象的集合(里面的数字都是对象)。  
> 而PyTorch张量和Numpy数组通常是连续的内存块视图，这些内存块包含未装箱的`C`数字类型，而不是`Python`对象。
>
> 如：10000个浮点数的一维张量，只需要40000个连续字节，再加上元数据的小量开销。

### 1.2 zeros和ones

In [10]:
b = torch.zeros(5)
b

tensor([0., 0., 0., 0., 0.])

In [11]:
b.shape, b.dtype

(torch.Size([5]), torch.float32)

In [12]:
c = torch.ones(6)
c

tensor([1., 1., 1., 1., 1., 1.])

In [13]:
c.shape, c.dtype

(torch.Size([6]), torch.float32)

### 1.3 修改dtype

In [14]:
a1 = torch.tensor([1.0, 2.0, 3.0], dtype=torch.float)
a1

tensor([1., 2., 3.])

In [15]:
a1.shape, a1.dtype

(torch.Size([3]), torch.float32)

In [16]:
# 修改为double，float64
a1.to(torch.double)

tensor([1., 2., 3.], dtype=torch.float64)

In [17]:
a1.dtype

torch.float32

In [18]:
a2 = torch.tensor([1, 2, 3], dtype=torch.int16)
a2

tensor([1, 2, 3], dtype=torch.int16)

In [19]:
a2.shape, a2.dtype

(torch.Size([3]), torch.int16)

In [20]:
# 调整dtype为int32
a2.to(torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [21]:
a2.shape, a2.dtype

(torch.Size([3]), torch.int16)

### 1.4 索引张量

In [22]:
list_01 = [
    [1.0, 2.0, 3.0],
    [4.0, 5.0, 6.0],
    [7.0, 8.0, 9.0]
]

In [23]:
t = torch.tensor(list_01)
t

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [24]:
t.shape, t.dtype

(torch.Size([3, 3]), torch.float32)

In [25]:
# 获取第2行
t[1]

tensor([4., 5., 6.])

In [26]:
# 获取第2行，方式2
t[1,:]

tensor([4., 5., 6.])

In [27]:
# 修改第2行的第2个数字
t[1][1] = 5.5
t

tensor([[1.0000, 2.0000, 3.0000],
        [4.0000, 5.5000, 6.0000],
        [7.0000, 8.0000, 9.0000]])

In [28]:
t[1:]

tensor([[4.0000, 5.5000, 6.0000],
        [7.0000, 8.0000, 9.0000]])

In [29]:
t[:,0]

tensor([1., 4., 7.])

In [30]:
t[:,:2]

tensor([[1.0000, 2.0000],
        [4.0000, 5.5000],
        [7.0000, 8.0000]])

### 1.5 张量的存储视图

张量中的值被分配到由`torch.Storage`实例所管理的连续内存块中。  
存储区是由数字数组组成的一维数组，即包含给定类型的数字的连续块，例如`float32`或`int16`。

新的设计将迁移向无存储类型(`UntypedStorage`)，意味着底层存储将不再于特定类型直接关联，从而允许更灵活的数据操作。

In [31]:
t = torch.tensor([1.0, 2.0, 3.0])

In [32]:
t, t.dtype

(tensor([1., 2., 3.]), torch.float32)

In [33]:
# isinstance(t.storage(), torch.Storage) # 会有警告storage方法已经不推荐
isinstance(t.untyped_storage(), torch.UntypedStorage)

True

In [34]:
t.untyped_storage()

 0
 0
 128
 63
 0
 0
 0
 64
 0
 0
 64
 64
[torch.storage.UntypedStorage(device=cpu) of size 12]

In [35]:
t = t.to(torch.float64)

In [36]:
t

tensor([1., 2., 3.], dtype=torch.float64)

In [37]:
t.untyped_storage()

 0
 0
 0
 0
 0
 0
 240
 63
 0
 0
 0
 0
 0
 0
 0
 64
 0
 0
 0
 0
 0
 0
 8
 64
[torch.storage.UntypedStorage(device=cpu) of size 24]