## 02. 张量的元数据：大小、偏移量和步长

为了在存储区中建议索引，张量依赖一些元数据：大小、偏移量和步长。

In [1]:
import torch

In [2]:
t1 = torch.tensor([
    [1.0, 2.0, 3.0],
    [4.0, 5.0, 6.0],
    [7.0, 8.0, 9.0]
])
t1

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [3]:
# 从t1中获取个子张量
t2 = t1[1]
t2

tensor([4., 5., 6.])

In [4]:
t1.untyped_storage() == t2.untyped_storage()

True

In [5]:
id(t1.untyped_storage()) == id(t2.untyped_storage())

True

**可以看到`t1`和`t2`是共用一个存储区的。**

In [6]:
t2.untyped_storage()

 0
 0
 128
 63
 0
 0
 0
 64
 0
 0
 64
 64
 0
 0
 128
 64
 0
 0
 160
 64
 0
 0
 192
 64
 0
 0
 224
 64
 0
 0
 0
 65
 0
 0
 16
 65
[torch.storage.UntypedStorage(device=cpu) of size 36]

### 2.1 张量的大小

In [7]:
# 查看张量的大小，shape、类型
t1.size(), t1.shape, t1.dtype

(torch.Size([3, 3]), torch.Size([3, 3]), torch.float32)

In [8]:
t2.size(), t2.shape, t2.dtype

(torch.Size([3]), torch.Size([3]), torch.float32)

**函数`size()`是`Size`类的一个实例，其所包含的信息与张量对象的`shape`属性所包含的信息是一样的。**

In [9]:
t2.size() == t2.shape

True

In [10]:
id(t2.size()) == id(t2.shape)

True

### 2.2 张量的偏移量

In [11]:
# 查看张量的偏移量
t1.storage_offset()

0

In [12]:
# 查看张量t2的偏移量
t2.storage_offset()

3

**得到张量`t2`的存储区域中的偏移量是`3`, 这是因为我们需要跳过`1`个点，该点有`3`个元素。**

### 2.3 张量的步长

In [13]:
t1.stride(), t2.stride()

((3, 1), (1,))

**步长是一个元组，指示当索引在每个维度中增加1时，在存储区中必须跳过的元素数量。**   
例如：`t1`的步长为`(3.1)`。

### 2.4 克隆新的张量

clone()之前让我们，修改t2中的某个元素，看下t1是否也修改了。

In [14]:
t2[1] = 5.2222
t2

tensor([4.0000, 5.2222, 6.0000])

In [15]:
t1

tensor([[1.0000, 2.0000, 3.0000],
        [4.0000, 5.2222, 6.0000],
        [7.0000, 8.0000, 9.0000]])

**我们看到t1也修改了一个元素`t[1][1]`。** 

In [16]:
# 我们复制一个新的张量
t3 = t1[1].clone()
t3

tensor([4.0000, 5.2222, 6.0000])

In [17]:
# 查看t3的：大小、偏移量、步长
t3.size(), t3.storage_offset(), t3.stride(),

(torch.Size([3]), 0, (1,))

In [18]:
t3.untyped_storage() == t1.untyped_storage()

False

可以看到我们加了`.clone()`就是使用新的存储区了，而不是在`t1`原有的存储区上。  
那么我们修改t3中的元素，对t1不会有影响。

In [19]:
t3[1] = 5.1111
t3

tensor([4.0000, 5.1111, 6.0000])

In [20]:
t1

tensor([[1.0000, 2.0000, 3.0000],
        [4.0000, 5.2222, 6.0000],
        [7.0000, 8.0000, 9.0000]])