## 03. 张量的转置

In [15]:
import torch
import numpy as np

### 3.1 无复制转置

In [35]:
t1 = torch.tensor([
    [1.0, 2.0],
    [3.0, 4.0],
    [5.0, 6.0],
    [7.0, 8.0]
])
t1

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])

我们现在有一个张量`t1`，它在行中有单独的点，在列中有2列。   
现在我们想对其转置，使各个点都在列中，行变成了列。   
我们可以用PyTorch的`transpose()`方法，其简写方法是`t()`。

In [36]:
t1_t = t1.t()

In [37]:
t1_t

tensor([[1., 3., 5., 7.],
        [2., 4., 6., 8.]])

In [38]:
# 我们看下其存储区是否相等
id(t1.untyped_storage()) == id(t1_t.untyped_storage())

True

In [39]:
t1.shape, t1_t.shape

(torch.Size([4, 2]), torch.Size([2, 4]))

In [40]:
t1_t.storage_offset(), t1_t.stride()

(0, (1, 2))

t1,t1_t对应存储区中存储数据是：`storage = [1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0]`。   
访问一个二维张量的位置`(i, j)`的元素。其在存储区中的位置计算方式是：  
```bash
storage_offset() + stride()[0] * i + stride()[1]*j
```
那么我们现在计算`t1_t[1][1]`的存储位置:那应该就是`0 + 1 * 1 + 2 * 1 = 3`. 那对应在storage中就是4.0。   
现在我们用代码验证一下：

In [42]:
t1_t[1][1]

tensor(4.)

### 3.2 高维转置

`PyTorch`中的转置不限于矩阵。   
我们可以通过给`transpose`方法指定2个维度，即翻转形状和步长，来转置一个多维的数组。

In [26]:
data = np.random.randn(3, 4, 5)

In [27]:
t2 = torch.from_numpy(data).to(torch.float32)
t2

tensor([[[-0.9637, -0.0494, -1.0926, -0.1722,  0.3644],
         [ 2.3729, -0.2983,  0.1500,  0.0080, -0.8597],
         [ 1.4903, -0.8529,  1.4636, -1.8240,  1.2810],
         [ 0.4113, -1.1085, -1.4265, -0.8645,  0.0948]],

        [[ 0.6882, -0.2303, -1.8118,  0.4577, -0.4630],
         [-1.2043, -1.0640, -2.0392,  0.1612, -0.7351],
         [ 1.2898,  0.7702,  0.9587, -2.2740,  0.3213],
         [-0.5870, -0.5845,  0.1563, -0.4830,  1.4455]],

        [[-1.0441,  0.0051,  0.7348,  1.4635, -0.0647],
         [ 0.8071, -0.4299, -1.4428, -1.0870, -1.9582],
         [-0.2964,  0.8078,  0.4513,  1.4347,  0.1227],
         [-0.9368,  1.6107, -0.5897, -1.5009, -1.5033]]])

In [28]:
# 查看张量的形状、步长
t2.shape, t2.stride()

(torch.Size([3, 4, 5]), (20, 5, 1))

In [29]:
t2_t = t2.transpose(0, 2)
t2_t

tensor([[[-0.9637,  0.6882, -1.0441],
         [ 2.3729, -1.2043,  0.8071],
         [ 1.4903,  1.2898, -0.2964],
         [ 0.4113, -0.5870, -0.9368]],

        [[-0.0494, -0.2303,  0.0051],
         [-0.2983, -1.0640, -0.4299],
         [-0.8529,  0.7702,  0.8078],
         [-1.1085, -0.5845,  1.6107]],

        [[-1.0926, -1.8118,  0.7348],
         [ 0.1500, -2.0392, -1.4428],
         [ 1.4636,  0.9587,  0.4513],
         [-1.4265,  0.1563, -0.5897]],

        [[-0.1722,  0.4577,  1.4635],
         [ 0.0080,  0.1612, -1.0870],
         [-1.8240, -2.2740,  1.4347],
         [-0.8645, -0.4830, -1.5009]],

        [[ 0.3644, -0.4630, -0.0647],
         [-0.8597, -0.7351, -1.9582],
         [ 1.2810,  0.3213,  0.1227],
         [ 0.0948,  1.4455, -1.5033]]])

In [30]:
t2_t.shape, t2_t.stride()

(torch.Size([5, 4, 3]), (1, 5, 20))

In [31]:
# 查看是否是连续的
t2.is_contiguous(), t2_t.is_contiguous()

(True, False)

In [32]:
# 查看是否是同一个存储区
id(t2.untyped_storage()) == id(t2_t.untyped_storage())

True