## 4. 张量的数学操作

### 4.1 张量的加法

和和差计算都比较简单，只需要将2个张量的各个响应元素相加或相减即可。

In [1]:
import torch

In [2]:
t1 = torch.tensor([
    [2.0, 2., 3.],
    [4.0, 4.0, 6.0],
    [3.0, 6.0, 9.0]
])
t2 = torch.tensor([
    [2.0, 4.0, 6.0],
    [8.0, 10.0, 12.0],
    [14.0, 16.0, 18.0]
])

In [3]:
t1, t2

(tensor([[2., 2., 3.],
         [4., 4., 6.],
         [3., 6., 9.]]),
 tensor([[ 2.,  4.,  6.],
         [ 8., 10., 12.],
         [14., 16., 18.]]))

In [4]:
# 加法
t12 = t1 + t2
t12

tensor([[ 4.,  6.,  9.],
        [12., 14., 18.],
        [17., 22., 27.]])

In [5]:
t12.shape, t12.dtype, t12.stride()

(torch.Size([3, 3]), torch.float32, (3, 1))

In [6]:
torch.add(t1, t2)

tensor([[ 4.,  6.,  9.],
        [12., 14., 18.],
        [17., 22., 27.]])

### 4.2 张量的减法

2个张量，各个响应的元素相减即可。

In [7]:
t1, t2

(tensor([[2., 2., 3.],
         [4., 4., 6.],
         [3., 6., 9.]]),
 tensor([[ 2.,  4.,  6.],
         [ 8., 10., 12.],
         [14., 16., 18.]]))

In [8]:
t1 - t2

tensor([[  0.,  -2.,  -3.],
        [ -4.,  -6.,  -6.],
        [-11., -10.,  -9.]])

In [9]:
t2 - t1

tensor([[ 0.,  2.,  3.],
        [ 4.,  6.,  6.],
        [11., 10.,  9.]])

In [10]:
torch.sub(t2, t1)

tensor([[ 0.,  2.,  3.],
        [ 4.,  6.,  6.],
        [11., 10.,  9.]])

### 4.3 张量的乘法

In [11]:
t1 * t2

tensor([[  4.,   8.,  18.],
        [ 32.,  40.,  72.],
        [ 42.,  96., 162.]])

In [12]:
t11 = torch.tensor([4.0, 5.0, 6.0])
t22 = torch.tensor([
    [1.0],
    [2.0],
    [3.0]
])
t11.shape, t22.shape

(torch.Size([3]), torch.Size([3, 1]))

#### 逐元素乘法

In [13]:
t1 * t2

tensor([[  4.,   8.,  18.],
        [ 32.,  40.,  72.],
        [ 42.,  96., 162.]])

In [14]:
t11 * t22, torch.mul(t11, t22)

(tensor([[ 4.,  5.,  6.],
         [ 8., 10., 12.],
         [12., 15., 18.]]),
 tensor([[ 4.,  5.,  6.],
         [ 8., 10., 12.],
         [12., 15., 18.]]))

In [15]:
t22 * t11, torch.mul(t22, t11)

(tensor([[ 4.,  5.,  6.],
         [ 8., 10., 12.],
         [12., 15., 18.]]),
 tensor([[ 4.,  5.,  6.],
         [ 8., 10., 12.],
         [12., 15., 18.]]))

#### 矩阵乘法
计算矩阵的积是，需要将左侧矩阵的行和右侧矩阵的列的元素一次相乘，然后将结果相加在一起。   
计算矩阵乘积时：左边的矩阵列数，要等于右边矩阵的行数。

In [16]:
t1, t2

(tensor([[2., 2., 3.],
         [4., 4., 6.],
         [3., 6., 9.]]),
 tensor([[ 2.,  4.,  6.],
         [ 8., 10., 12.],
         [14., 16., 18.]]))

In [17]:
t1[0], t2[:,0]

(tensor([2., 2., 3.]), tensor([ 2.,  8., 14.]))

In [18]:
# t1,t2的矩阵乘法：那么左侧是t1, 右侧是t2
# 那么相乘的第0行0列，00个元素是：2 * 2 + 2 * 8 + 3 * 14 = 4 + 16 + 42 = 62
# 那么2.1个元素是： C21 = 3 * 4 + 6 * 10 + 9 * 16 = 12 + 60 + 144 = 216
torch.matmul(t1, t2)

tensor([[ 62.,  76.,  90.],
        [124., 152., 180.],
        [180., 216., 252.]])

In [19]:
torch.matmul(t2, t1)

tensor([[ 38.,  56.,  84.],
        [ 92., 128., 192.],
        [146., 200., 300.]])

In [20]:
t11, t22

(tensor([4., 5., 6.]),
 tensor([[1.],
         [2.],
         [3.]]))

In [21]:
# 4 * 1 + 5 * 2 + 6 * 3 = 32
torch.matmul(t11, t22)

tensor([32.])

### 4.4 张量的除法

In [22]:
t1 / t2

tensor([[1.0000, 0.5000, 0.5000],
        [0.5000, 0.4000, 0.5000],
        [0.2143, 0.3750, 0.5000]])

In [23]:
torch.div(t1, t2)

tensor([[1.0000, 0.5000, 0.5000],
        [0.5000, 0.4000, 0.5000],
        [0.2143, 0.3750, 0.5000]])