## 张量的数学计算--2个张量不同维度

In [1]:
import torch
torch.manual_seed(123456)
print("")

### 1. 先生成2个不同维度的张量

In [2]:
t1 = torch.ones(3, 1)
t1

tensor([[1.],
        [1.],
        [1.]])

In [3]:
t1 = t1 * torch.tensor([
    [1.0],
    [2.0],
    [3.0]
])
t1

tensor([[1.],
        [2.],
        [3.]])

In [4]:
# t2 = torch.rand(1, 3)
t2 = torch.tensor([[0.9038, 0.1368, 0.2698]])
t2

tensor([[0.9038, 0.1368, 0.2698]])

In [5]:
# 可以看到t1 和 t2 维度不一样
t1.shape, t2.shape

(torch.Size([3, 1]), torch.Size([1, 3]))

### 2. 计算其加减乘除

#### 2.1 加

In [6]:
t1 + t2

tensor([[1.9038, 1.1368, 1.2698],
        [2.9038, 2.1368, 2.2698],
        [3.9038, 3.1368, 3.2698]])

In [7]:
t2 + t1

tensor([[1.9038, 1.1368, 1.2698],
        [2.9038, 2.1368, 2.2698],
        [3.9038, 3.1368, 3.2698]])

#### 2.2 减

In [8]:
t1 - t2

tensor([[0.0962, 0.8632, 0.7302],
        [1.0962, 1.8632, 1.7302],
        [2.0962, 2.8632, 2.7302]])

In [9]:
t2 - t1

tensor([[-0.0962, -0.8632, -0.7302],
        [-1.0962, -1.8632, -1.7302],
        [-2.0962, -2.8632, -2.7302]])

#### 2.3 乘

In [10]:
t1 * t2

tensor([[0.9038, 0.1368, 0.2698],
        [1.8076, 0.2736, 0.5396],
        [2.7114, 0.4104, 0.8094]])

In [11]:
t2 * t1

tensor([[0.9038, 0.1368, 0.2698],
        [1.8076, 0.2736, 0.5396],
        [2.7114, 0.4104, 0.8094]])

#### 2.4 除法

In [12]:
t1 / t2

tensor([[ 1.1064,  7.3099,  3.7064],
        [ 2.2129, 14.6199,  7.4129],
        [ 3.3193, 21.9298, 11.1193]])

In [13]:
t2 / t1

tensor([[0.9038, 0.1368, 0.2698],
        [0.4519, 0.0684, 0.1349],
        [0.3013, 0.0456, 0.0899]])