## 5. 张量的归约操作

在PyTorch中，Tensor的归约操作是指：对Tensor(张量)的一个或多个维度进行聚合，从而得到一个具有较小维度的新张量。

In [1]:
import torch

In [2]:
t1 = torch.tensor([
    [1.0, 2.0],
    [3.0, 4.0]
])

t2 = torch.tensor([
    [1.0, 2.0, 3.0],
    [4.0, 5.0, 6.0]
])

In [3]:
t1, t1.shape

(tensor([[1., 2.],
         [3., 4.]]),
 torch.Size([2, 2]))

In [4]:
t2, t2.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.]]),
 torch.Size([2, 3]))

### 5.1 torch.sum()

计算张量中所有元素的和，可以指定一个或多个维度来计算部分和。

In [5]:
torch.sum(t2)

tensor(21.)

In [6]:
# dim=0,那么就是取出第0维行中的所有数据
t2[:, 0], t2[:, 1], t2[:, 2]

(tensor([1., 4.]), tensor([2., 5.]), tensor([3., 6.]))

In [7]:
torch.sum(t2, dim=0)

tensor([5., 7., 9.])

In [8]:
# dim=1，那么就是取出第1维，列中的所有数据
t2[0,:], t2[1,:]

(tensor([1., 2., 3.]), tensor([4., 5., 6.]))

In [9]:
torch.sum(t2, dim=1)

tensor([ 6., 15.])

### 5.2 torch.mean()

计算张量中所有元素的平均值，可以通过`dim`指定维度

In [10]:
t1

tensor([[1., 2.],
        [3., 4.]])

In [11]:
t1.mean()

tensor(2.5000)

In [12]:
# 沿着第0维的平均值
t1.mean(dim=0)

tensor([2., 3.])

In [13]:
# 沿着第1维的平均值
t1.mean(dim=1)

tensor([1.5000, 3.5000])

In [14]:
# dim=1全部取出
t1[0, :], t1[1,:]

(tensor([1., 2.]), tensor([3., 4.]))

In [15]:
t1.sum(dim=1) / t1.shape[1]

tensor([1.5000, 3.5000])

### 5.3 torch.min()和torch.max()

计算张量的最小值和最大值，传入dim的时候，这2个函数返回2个值，最小/最大值和它们的位置(索引)。

In [16]:
t2

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [17]:
t2.min(), t2.max()

(tensor(1.), tensor(6.))

In [18]:
torch.max(t2)

tensor(6.)

In [19]:
# 第0维的最小
t2.min(dim=0)

torch.return_types.min(
values=tensor([1., 2., 3.]),
indices=tensor([0, 0, 0]))

In [20]:
# 第0维的最大值
value, index = t2.max(dim=0)
value, index

(tensor([4., 5., 6.]), tensor([1, 1, 1]))

In [21]:
# 第1维的最大值
t2.max(dim=1)

torch.return_types.max(
values=tensor([3., 6.]),
indices=tensor([2, 2]))

### 5.4 torch.std()和torch.var()

计算张量的标准差和方差

In [22]:
t2

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [23]:
t2.std(), t2.var()

(tensor(1.8708), tensor(3.5000))

In [24]:
t2.std(dim=0), t2.var(dim=0)

(tensor([2.1213, 2.1213, 2.1213]), tensor([4.5000, 4.5000, 4.5000]))

In [25]:
t2.std(dim=1), t2.var(dim=1)

(tensor([1., 1.]), tensor([1., 1.]))

### 5.5 torch.norm()

计算张量的范数。可以计算L1、L2范数

In [26]:
t2

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [27]:
# 默认是L2范数
t2.norm()

tensor(9.5394)

In [28]:
# 计算L1范数（绝对值和）
t2.norm(p=1)

tensor(21.)

In [29]:
# 计算L2范数（欧几里得范数）
t2.norm(p=2)

tensor(9.5394)

### 5.6 torch.prod()

计算输入张量中所有元素的乘积

In [30]:
t2

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [31]:
torch.prod(t2)

tensor(720.)

In [32]:
torch.prod(t2, dim=0)

tensor([ 4., 10., 18.])

In [33]:
torch.prod(t2, dim=1)

tensor([  6., 120.])

### 5.7 torch.all()和torch.any()
分别检查张量中是否所有元素都为True（非零），或者是否有一个元素为True(非零)。    
这些操作常用于布尔张量。

In [34]:
t3 = torch.tensor([
    [True, True, False],
    [True, True, True],
    [False, False, False]
])

In [35]:
t3.shape, t3.dtype

(torch.Size([3, 3]), torch.bool)

In [36]:
torch.all(t3)

tensor(False)

In [37]:
torch.any(t3)

tensor(True)

In [38]:
torch.all(t3, dim=1), torch.all(t3, dim=0)

(tensor([False,  True, False]), tensor([False, False, False]))

In [39]:
torch.any(t3, dim=1), torch.any(t3, dim=0)

(tensor([ True,  True, False]), tensor([True, True, True]))