## torch.randperm随机打乱数据顺序

`permutation`是排列，排序的意思。  那么`randperm`就是随机排列。   

In [1]:
import torch
torch.manual_seed(123456)
print("")

In [2]:
torch.randperm(5)

tensor([0, 3, 1, 4, 2])

现在加入我们有了一个张量，我们想打乱其顺序，就可以使用到`randperm()`生成的张量作为索引，得到打乱后的张量数据。

In [3]:
# 先生成一个张量
data = torch.tensor([123.0, 456.0, 111.0, 222.0, 33.0, 999.0, 1.23])
data

tensor([123.0000, 456.0000, 111.0000, 222.0000,  33.0000, 999.0000,   1.2300])

In [4]:
# 计算data的长度
count = len(data)
count

7

In [5]:
# 现在我们获取一个随机的排列
permutation = torch.randperm(count)
permutation

tensor([2, 4, 6, 0, 5, 1, 3])

In [6]:
data[permutation]

tensor([111.0000,  33.0000,   1.2300, 123.0000, 999.0000, 456.0000, 222.0000])

> 到这里我们就获取到一个打乱顺序的数据了。